repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: docs/img/
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["-m", "3", "--tc"]
  - repo: https://github.com/grantjenks/blue
    rev: "v0.9.1"
    hooks:
      - id: blue
        args: ["-l", "120"]
        exclude: |
          (?x)^(
              quantdb/api.py|
              quantdb/ingest.py|ls
              sql;/.*
          )$
